#**Ejercicios de Aprendizaje**

###**01_Controles y Cumplimiento**

####¿La "Llave del Chaco" tiene actualmente este control activo?

**Evaluacion de controles**

In [22]:
import pandas as pd
from IPython.display import display

data_control = {
    "Si": ["", "", "", "", "X", "", "", "X", "", "", "", "X", "x", "X"],
    "No": ["X", "X", "X", "X", "", "X", "X", "", "X", "X", "X", "", "", ""],
    "Control": ["Privilegio Mínimo", "Planes de recuperación ante desastres", "Políticas de contraseñas", "Separación de funciones", "Firewall", "Sistema de detección de intrusiones (IDS)", "Backups", "Software antivirus", "Monitorización, mantenimiento e intervención manuales para sistemas heredados", "Cifrado", "Sistema de gestión de contraseñas", "Cerraduras (oficinas, escaparate, almacén)", "Vigilancia por circuito cerrado de televisión (CCTV)", "Detección/prevención de incendios (alarma de incendios, sistema de rociadores, etc.)"],
    "Explicación": ["Actualmente, todos los empleados tienen acceso a los datos de los clientes; Los privilegios deben limitarse para reducir el riesgo de una brecha.", "No existen planes de recuperación ante desastres. Estas deben implementarse para garantizar la continuidad del negocio.", "Los requisitos de contraseña para empleados son mínimos, lo que podría permitir a un actor amenazante acceder más fácilmente a datos seguros u otros activos a través del equipo de trabajo o la red interna.", "Debe implementarse para reducir la posibilidad de fraude o acceso a datos críticos, ya que el CEO de la empresa actualmente gestiona las operaciones diarias y la nómina.", "El firewall existente bloquea el tráfico basándose en un conjunto de reglas de seguridad adecuadamente definidas.", "El departamento de IT necesita un IDS para ayudar a identificar posibles intrusiones de actores amenazantes.", "El departamento de IT necesita tener copias de seguridad de datos críticos en caso de una brecha de seguridad para garantizar la continuidad del negocio.", "El software antivirus se instala y supervisa regularmente por el departamento de IT.", "La lista de activos señala el uso de sistemas heredados. La evaluación de riesgos indica que estos sistemas están monitorizados y mantenidos, pero no existe un calendario regular para esta tarea y los procedimientos/políticas relacionadas con la intervención no están claros, lo que podría poner estos sistemas en riesgo de una brecha.", "Actualmente, no se utiliza cifrado; Implementarlo proporcionaría mayor confidencialidad de la información sensible.", "Actualmente no existe un sistema de gestión de contraseñas; implementar este control mejoraría la productividad del departamento de IT y de otros empleados en caso de problemas con la contraseña.", "La ubicación física de la tienda, que incluye las oficinas principales, la fachada y el almacén de productos, cuenta con suficientes cerraduras.", "Las cámaras de seguridad están instaladas y funcionando en la ubicación física de la tienda.", "La ubicación física de 'Llave del Chaco' cuenta con un sistema funcional de detección y prevención de incendios."]
}
tabla_control = pd.DataFrame(data_control)

pd.set_option('display.max_colwidth', None)

display(tabla_control.style.hide(axis="index"))

**Evaluacion de controles**

*Estándar de Seguridad de Datos de la Industria de Tarjetas de Pago (PCI DSS)*

In [21]:
data_compliance = {
    "Si": ["", "", "", ""],
    "No": ["X", "X", "X", "X"],
    "Buenas Practicas": ["Solo los usuarios autorizados tienen acceso a la información de las tarjetas de crédito de los clientes.", "La información de la tarjeta de crédito se acepta, procesa, transmite y almacena internamente, en un entorno seguro.", "Implementa procedimientos de cifrado de datos para proteger mejor los puntos de contacto y datos de las transacciones con tarjeta de crédito.", "Adopta políticas seguras de gestión de contraseñas."],
    "Explicación": ["Actualmente, todos los empleados tienen acceso a los datos internos de la empresa.", "La información de las tarjetas de crédito no está cifrada y todos los empleados tienen acceso actualmente a datos internos, incluida la información de las tarjetas de crédito de los clientes.", "Actualmente, la empresa no utiliza cifrado para garantizar mejor la confidencialidad de la información financiera de los clientes.", "Las políticas de contraseñas son nominales y actualmente no existe ningún sistema de gestión de contraseñas."]
}
tabla_compliance = pd.DataFrame(data_compliance)

pd.set_option('display.max_colwidth', None)

display(tabla_compliance.style.hide(axis="index"))

*Reglamento General de Protección de Datos (RGPD)*

In [20]:
data_rgpd = {
    "Si": ["", "X", "", "X"],
    "No": ["X", "", "X", ""],
    "Buenas Practicas": ["Los datos de los clientes de la UE se mantienen privados y protegidos.", "Existe un plan para notificar a los clientes de la UE en un plazo de 72 horas si sus datos son comprometidos o hay una brecha.", "Asegúrate de que los datos estén correctamente clasificados e inventariados.", "Hacer cumplir políticas, procedimientos y procesos de privacidad para documentar y mantener correctamente los datos."],
    "Explicación": ["Actualmente, la empresa no utiliza cifrado para garantizar mejor la confidencialidad de la información financiera de los clientes.", "Existe un plan para notificar a los clientes de la UE en un plazo de 72 horas tras una brecha de datos.", "Los activos actuales han sido inventariados/listados, pero no clasificados.", "Se han desarrollado y aplicado políticas de privacidad, procedimientos y procesos entre los miembros del equipo de IT y otros empleados, según sea necesario."]
}
tabla_rgpd = pd.DataFrame(data_rgpd)

pd.set_option('display.max_colwidth', None)

display(tabla_rgpd.style.hide(axis="index"))

*Controles de Sistemas y Organizaciones (SOC tipo 1, SOC tipo 2)*

In [23]:
data_soc = {
    "Sí": ["", "", "X", ""],
    "No": ["X", "X", "", "X"],
    "Buenas prácticas": [
        "Se establecen las políticas de acceso de usuario.",
        "Los datos sensibles (PII/SPII) son confidenciales/privados.",
        "La integridad de los datos garantiza que los datos sean consistentes, completos, precisos y hayan sido validados.",
        "Los datos están disponibles para las personas autorizadas a acceder a ellos."
    ],
    "Explicación": [
        "Actualmente, no existen controles de Privilegio Mínimo ni de separación de funciones; Todos los empleados tienen acceso a los datos almacenados internamente.",
        "Actualmente, el cifrado no se utiliza para garantizar mejor la confidencialidad de la PII/SPII.",
        "La integridad de los datos está en marcha.",
        "Aunque los datos están disponibles para todos los empleados, la autorización debe limitarse solo a las personas que necesitan acceso para realizar su trabajo."
    ]
}
tabla_soc = pd.DataFrame(data_soc)

pd.set_option('display.max_colwidth', None)

display(tabla_soc.style.hide(axis="index"))

**Recomendaciones:**
Es necesario implementar múltiples controles para mejorar la postura de seguridad de 'La Llave del Chaco' y garantizar mejor la confidencialidad de la información sensible, incluyendo: **Privilegio Mínimo**, **planes de recuperación ante desastres**, **políticas de contraseñas**, **separación de funciones**, un **IDS**, **gestión continua del sistema heredado**, **cifrado** y un **sistema de gestión de contraseñas**.

Para abordar las lagunas en el cumplimiento, 'La Llave del Chaco' necesita implementar controles como el Privilegio Mínimo, la separación de funciones y el cifrado. La empresa también necesita clasificar adecuadamente los activos, identificar controles adicionales que puedan necesitar implementarse para mejorar su postura de seguridad y proteger mejor la información sensible.