<a href="https://colab.research.google.com/github/CMFdata/CyberSecurityProjects/blob/main/EN01_controls_and_compliance.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#**Learning Exercises**

###**01_Controls and Compliance**

####Does 'La Llave del Chaco' currently have this control active?

**Control Evaluation**

In [5]:
import pandas as pd
from IPython.display import display

data_control = {
    "Yes": ["", "", "", "", "X", "", "", "X", "", "", "", "X", "x", "X"],
    "No": ["X", "X", "X", "X", "", "X", "X", "", "X", "X", "X", "", "", ""],
    "Control": ["Minimum Privilege", "Disaster Recovery Plans", "Password Policies", "Segregation of Duties", "Firewall", "Intrusion Detection System (IDS)", "Backups", "Antivirus Software", "Manual monitoring, maintenance, and intervention for legacy systems", "Encryption", "Password Management System", "Locks (offices, storefront, warehouse)", "Closed Circuit Television (CCTV) Surveillance", "Fire detection/prevention (fire alarm, sprinkler system, etc.)"],
    "Explanation": ["Currently, all employees have access to customer data; Privileges must be limited to reduce the risk of a breach.", "Disaster recovery plans do not exist. These must be implemented to ensure business continuity.", "Password requirements for employees are minimal, which could allow a threat actor to more easily access secure data or other assets through work equipment or the internal network.", "Must be implemented to reduce the possibility of fraud or access to critical data, as the company's CEO currently manages daily operations and payroll.", "The existing firewall blocks traffic based on a set of properly defined security rules.", "The IT department needs an IDS to help identify potential intrusions from threat actors.", "The IT department needs to have critical data backups in case of a security breach to ensure business continuity.", "Antivirus software is installed and regularly monitored by the IT department.", "The asset list indicates the use of legacy systems. The risk assessment indicates that these systems are monitored and maintained, but there is no regular schedule for this task and the procedures/policies related to intervention are unclear, which could put these systems at risk of a breach.", "Currently, encryption is not used; Implementing it would provide greater confidentiality of sensitive information.", "Currently, there is no password management system; implementing this control would improve the productivity of the IT department and other employees in case of password issues.", "The physical location of the store, which includes the main offices, the facade, and the product warehouse, has sufficient locks.", "Security cameras are installed and functioning at the physical store location.", "'La Llave del Chaco' physical location has a functional fire detection and prevention system."]
}
tabla_control = pd.DataFrame(data_control)

pd.set_option('display.max_colwidth', None)

display(tabla_control.style.hide(axis="index"))

**Control Evaluation**

*Payment Card Industry Data Security Standard (PCI DSS)*

In [7]:
data_compliance = {
    "Yes": ["", "", "", ""],
    "No": ["X", "X", "X", "X"],
    "Good Practices": ["Only authorized users have access to customer credit card information.", "Credit card information is accepted, processed, transmitted, and stored internally, in a secure environment.", "Implement data encryption procedures to better protect credit card transaction data and touchpoints.", "Adopt secure password management policies."],
    "Explanation": ["Currently, all employees have access to internal company data.", "Credit card information is not encrypted, and all employees currently have access to internal data, including customer credit card information.", "Currently, the company does not use encryption to better ensure the confidentiality of customer financial information.", "Password policies are nominal, and no password management system currently exists."]
}
tabla_compliance = pd.DataFrame(data_compliance)

pd.set_option('display.max_colwidth', None)

display(tabla_compliance.style.hide(axis="index"))

*General Data Protection Regulation (GDPR)*

In [8]:
data_rgpd = {
    "Yes": ["", "X", "", "X"],
    "No": ["X", "", "X", ""],
    "Good Practices": ["EU customer data is kept private and protected.", "There is a plan to notify EU customers within 72 hours if their data is compromised or there is a breach.", "Ensure data is properly classified and inventoried.", "Enforce privacy policies, procedures, and processes to properly document and maintain data."],
    "Explanation": ["Currently, the company does not use encryption to better ensure the confidentiality of customer financial information.", "There is a plan to notify EU customers within 72 hours of a data breach.", "Current assets have been inventoried/listed, but not classified.", "Privacy policies, procedures, and processes have been developed and implemented among IT team members and other employees, as needed."]
}
tabla_rgpd = pd.DataFrame(data_rgpd)

pd.set_option('display.max_colwidth', None)

display(tabla_rgpd.style.hide(axis="index"))

*System and Organization Controls (SOC type 1, SOC type 2)*

In [9]:
data_soc = {
    "Yes": ["", "", "X", ""],
    "No": ["X", "X", "", "X"],
    "Good Practices": [
        "User access policies are established.",
        "Sensitive data (PII/SPII) is confidential/private.",
        "Data integrity ensures that data is consistent, complete, accurate, and has been validated.",
        "Data is available to authorized individuals who need to access it."
    ],
    "Explanation": [
        "Currently, there are no Minimum Privilege or segregation of duties controls; All employees have access to internally stored data.",
        "Currently, encryption is not used to better ensure the confidentiality of PII/SPII.",
        "Data integrity is in place.",
        "Although data is available to all employees, authorization should be limited only to individuals who need access to perform their work."
    ]
}
tabla_soc = pd.DataFrame(data_soc)

pd.set_option('display.max_colwidth', None)

display(tabla_soc.style.hide(axis="index"))

**Recommendations:**
Multiple controls need to be implemented to improve 'La Llave del Chaco's security posture and better ensure the confidentiality of sensitive information, including: **Minimum Privilege**, **disaster recovery plans**, **password policies**, **segregation of duties**, an **IDS**, **continuous legacy system management**, **encryption**, and a **password management system**.

To address compliance gaps, 'La Llave del Chaco' needs to implement controls such as Minimum Privilege, segregation of duties, and encryption. The company also needs to properly classify assets, identify additional controls that may need to be implemented to improve its security posture and better protect sensitive information.