<a href="https://colab.research.google.com/github/CMFdata/CyberSecurityProjects/blob/main/EN02_Network_Traffic_Analysis.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#**Learning Exercises**

###**02_Network Traffic Analysis**

*A. Cybersecurity Incident Report: Network Traffic Analysis*

In [1]:
import pandas as pd

data_01 = {
    "Provide a summary of the problem found in the DNS and ICMP traffic log": [
        "A. As part of the DNS protocol, the UDP protocol was used to contact the DNS server and retrieve the IP address of the yummyrecipesforme.com domain name. The ICMP protocol was used to respond with an error message, indicating problems contacting the DNS server.",
        "B. The UDP message from your browser to the DNS server is shown in the first two lines of each log event. The ICMP error response from the DNS server to your browser is shown in the third and fourth lines of each log event with the error message: 'udp port 53 unreachable'. Since port 53 is associated with DNS protocol traffic, we know this is a DNS server issue. Problems running the DNS protocol are even more evident because the plus sign after query ID 35084 indicates flags with the UDP message and the 'A?' symbol indicates flags when performing DNS protocol operations.",
        "C. Due to the ICMP error response message about port 53, it is highly likely that the DNS server is not responding. This assumption is further supported by the flags associated with the outgoing UDP message and the domain name retrieval."
    ],
    "Explanation": [
        "A. Includes a brief summary of tcpdump log analysis and identifies which protocols were used for network traffic. The scenario summarizes the problem and identifies the protocols used. The scenario states: 'To load the web page, your browser first sends a query to a DNS server via the UDP protocol to retrieve the IP address of the website's domain name; this is part of the DNS protocol... The analyzer shows that when you send UDP packets to the DNS server, you receive ICMP packets containing the error message: udp port 53 unreachable.",
        "B. Provides some details about what was indicated in the log. The first and second steps of the scenario section indicate that you performed a network analysis using tcpdump, which recorded UDP packets from your source computer to the DNS server's IP address and port (203.0.113.2.domain). It also recorded ICMP error responses from the DNS server back to your computer with the error message 'udp port 53 unreachable.' We mentioned in the sixth step that port 53 is a port for the DNS service, which means this is a DNS server issue. We included more signs of DNS performance issues in the fifth step of the scenario: The plus sign after the query ID indicates that there are flags associated with the UDP message. The 'A?' indicates a flag associated with the DNS request for an A record, where an A record maps a domain name to an IP address.",
        "C. Interprets the problems found in the log. The Scenario section (or a quick internet search for 'port 53') will show that this port number is commonly used for communications with DNS protocols. Since port 53 is unreachable and that port is commonly used for communications with DNS servers, it can be concluded that the DNS server is unreachable or 'not responding.' This could be caused by a DoS attack against the DNS server, for example."
    ]
}

tabla_01 = pd.DataFrame(data_01)

pd.set_option('display.max_colwidth', None)

display(tabla_01.style.hide(axis="index"))

In [2]:
data_02 = {
    "Explain the data analysis and provide at least one cause of the incident": [
        "D. The incident occurred today at 1:24 p.m.",
        "E. Customers notified the organization that they received the 'destination port unreachable' message when trying to visit the yummyrecipesforme.com website.",
        "F. The cybersecurity team providing IT services to their client organization is currently investigating the issue so that customers can access the website again.",
        "G. In our investigation into the problem, we performed packet detection tests using tcpdump. In the resulting log file, we discovered that DNS port 53 was inaccessible.",
        "H. The next step is to identify whether the DNS server is down or if traffic to port 53 is blocked by the firewall.",
        "I. The DNS server could be down due to a successful denial-of-service attack or a misconfiguration."
    ],
    "Explanation": [
        "D. Indicates when the problem was first reported. This information was obtained from the timestamps in the log file. In the log, this is the first sequence of numbers shown: 13:24:32.192571. This shows the time 1:24 p.m., 32.192571 seconds, with the time in 24-hour format. The scenario indicates that this event occurred today.",
        "E. Provides the scenario, events, and symptoms identified when it was first reported. The scenario indicates that a handful of clients contacted your company to report that they could not access the company's website and saw the 'destination port unreachable' error after waiting for the page to load.",
        "F. Explains the current status of the problem. The Scenario states that, 'This incident, meanwhile, is being handled by security engineers after you and other analysts have reported the issue to your direct supervisor.'",
        "G. Describes the information discovered by investigating the problem so far. It offers a concise summary of what you did to investigate the problem. The scenario states: You visit the website and also receive the 'destination port unreachable' error. Then, you load your network analysis tool, tcpdump and reload the web page. This time, you receive many packets in your network analyzer. In the analyzer, you send UDP packets and receive an ICMP response to return to the host. The results contain an error message: 'udp port 53 unreachable'.",
        "H. Lists the next steps for troubleshooting and problem resolution. The next step in troubleshooting is to determine if the DNS server is not working correctly. If the DNS server is fine, the team should review the firewall configuration to see if anyone has changed the configuration to block network traffic on port 53. Firewalls offer the ability to block network traffic on specific ports. Port blocking can be used to stop or prevent an attack.",
        "I. Provides the suspected root cause of the problem. Previously, you learned about various types of denial-of-service (DoS) attacks. The goal of a DoS attack is to send a flood of information to a network device, such as a DNS server, to block it or prevent it from responding to legitimate network traffic. It is possible that an attacker has disabled the DNS server with a DoS attack. Alternatively, someone on your team could have made a configuration change to the firewall that blocked port 53."
    ]
}

tabla_02 = pd.DataFrame(data_02)

pd.set_option('display.max_colwidth', None)

display(tabla_02.style.hide(axis="index"))

---

*B. Security Incident Report*

**Section 1: Identify the network protocol involved in the incident**

The protocol involved in the incident is the Hypertext Transfer Protocol (HTTP). Since the problem was accessing the web server for yummyrecipesforme.com, we know that requests to web servers for web pages involve http traffic. Furthermore, when we ran tcpdump and accessed the yummyrecipesforme.com website, the corresponding tcpdump log file showed the use of the http protocol when contacting the server. It is observed that the malicious file is transported to users' computers using the HTTP protocol at the application layer.

**Section 2: Document the incident**

Several customers contacted the website's help desk indicating that, upon visiting it, they were asked to download and run a file containing access to new recipes. Their personal computers have run slowly ever since. The website owner tried to log in to the web server but noticed that they were locked out of their account.

The cybersecurity analyst used a sandbox environment to open the website without affecting the company's network. Then, the analyst ran tcpdump to capture network traffic packets generated by interacting with the website. The analyst was asked to download a file that claimed it would give access to free recipes, accepted the download, and executed it. The browser then redirected the analyst to a fake website (greatrecipesforme.com).

The cybersecurity analyst inspected the tcpdump log and observed that the browser initially requested the IP address of the yummyrecipesforme.com website. Once the connection to the website was established via the HTTP protocol, the analyst recalled having downloaded and executed the file. The logs showed a sudden change in network traffic when the browser requested a new IP address for the URL greatrecipesforme.com. The network traffic was then redirected to the new IP address of the greatrecipesforme.com website.

The senior cybersecurity professional analyzed the source code of the websites and the downloaded file. The analyst discovered that an attacker had manipulated the website to add code that incited users to download a malicious file disguised as a browser update. Since the website owner stated that they had been locked out of their administrator account, the team believes that the attacker used a brute-force attack to access the account and change the administrator password. The execution of the malicious file compromised the end users' computers.

**Section 3: Recommend remediation for brute-force attacks**

One security measure the team plans to implement to protect against brute-force attacks is to prevent the use of previous passwords. Given that the vulnerability that led to this attack was the attacker's ability to use a default password to log in, it is important that we prevent old passwords, such as default ones, from being used to reset the password. Another supporting measure is to require more frequent password updates, so that in case an unauthorized person learns the password, it is less likely that they can use it if it is updated soon. Finally, another useful solution is to implement two-factor authentication (2FA). 2FA authentication requires authentication via password and also confirming a one-time passcode (OTP) sent to your email or phone. Once the user confirms their identity through their login credentials and the OTP, they will have access to the system. Any malicious actor attempting a brute-force attack will likely not have access to the system because it requires additional authentication.

---

*C. Security Risk Assessment*

**Hardening tools and methods to implement**

Three hardening tools the organization can use to address the identified vulnerabilities include:
1.   Implementation of multi-factor authentication (MFA)
2.   Establishment and enforcement of strong password policies
3.   Regular firewall maintenance

MFA requires users to use more than one form of identification and credential verification before accessing an application. Some MFA methods include fingerprint scans, ID cards, PIN numbers, and passwords.

Password policies can be refined to include rules on password length, a list of acceptable characters, and a warning to discourage password sharing. They can also include rules on failed login attempts, such as the user losing network access after five failed attempts.

Firewall maintenance involves regularly reviewing and updating security configurations to anticipate potential threats.

**Recommendations**

Enforcing multi-factor authentication (**MFA**) adds an additional layer of security beyond just the password. This will reduce the likelihood of a malicious actor being able to access a network through a brute-force or related attack, as additional effort is required to authenticate in more than one way. MFA can also reduce the likelihood of people sharing passwords. Since the recipient of the shared password would need to possess additional authentication in addition to the password, MFA makes sharing passwords less useful, making them less likely to be shared.

Creating and enforcing a password policy within the company will make it increasingly difficult for malicious actors to access the network. Policies such as suspending an account after a certain number of login attempts can prevent successful brute-force attacks. Increasing password complexity, requiring more frequent updates, and not allowing passwords to be reused also helps curb the infiltration of malicious actors into the network.

Firewall maintenance should be done regularly. Network administrators must ensure that firewall rules reflect the most up-to-date standards for allowed and denied traffic. Traffic from suspicious sources should be included in a denied traffic list. Firewall rules should be updated whenever a security event occurs, especially an event that allows suspicious traffic into the network. This measure can be used to protect against various DoS (Denial-of-Service) and DDoS (Distributed Denial-of-Service) attacks.

---

*D. Incident Report Analysis*

**Summary:**

The company experienced a security event when all network services suddenly stopped responding. The cybersecurity team found that the outage was caused by a distributed denial-of-service (DDoS) attack via a flood of incoming ICMP packets. The team responded by blocking the attack and shutting down all non-critical network services, so that critical services could be restored.

In [3]:
data_report = {
    "NIST CSF": [
        "Identify",
        "Protect",
        "Detect",
        "Respond",
        "Recover"
    ],
    "Description": [
        "A malicious actor or actors attacked the company with an ICMP flood attack. The entire internal network was affected. All critical network resources had to be secured and restored to a functional state.",
        "The cybersecurity team implemented a new firewall rule to limit the rate of incoming ICMP packets and an IDS/IPS system to filter some ICMP traffic based on suspicious characteristics.",
        "The cybersecurity team configured source IP address verification in the firewalls to check for spoofed IP addresses in incoming ICMP packets and implemented network monitoring software to detect abnormal traffic patterns.",
        "For future security events, the cybersecurity team will isolate affected systems to prevent further network disruptions. They will attempt to restore any critical systems and services that have been disrupted by the event. Then, the team will analyze network logs to check for suspicious or abnormal activity. The team will also report all incidents to senior management and relevant legal authorities, if applicable.",
        "To recover from an ICMP flood DDoS attack, it is necessary to restore access to network services to a normal operating state. In the future, external ICMP flood attacks can be blocked at the firewall. Then, all non-critical network services should be stopped to reduce internal network traffic. Next, critical network services should be restored first. Finally, once the ICMP packet flood has subsided, all non-critical network systems and services can be brought back online."
    ]
}

tabla_report = pd.DataFrame(data_report)

pd.set_option('display.max_colwidth', None)

display(tabla_report.style.hide(axis="index"))