#**Ejercicios de Aprendizaje**

###**02_Analisis de trafico de redes**

*A. Informe de incidente de ciberseguridad: análisis del tráfico de red*

In [12]:
import pandas as pd

data_01 = {
    "Proporcionar un resumen del problema encontrado en el registro de tráfico DNS e ICMP": ["A.	Como parte del protocolo DNS, el protocolo UDP se utilizaba para contactar con el servidor DNS y recuperar la dirección IP del nombre de dominio de yummyrecipesforme.com. El protocolo ICMP se utilizaba para responder con un mensaje de error, indicando problemas al contactar con el servidor DNS.", "B.	El mensaje UDP que va de tu navegador al servidor DNS se muestra en las dos primeras líneas de cada evento de registro. La respuesta al error ICMP del servidor DNS a tu navegador se muestra en la tercera y cuarta línea de cada evento de registro con el mensaje de error: 'puerto udp 53 inaccesible'. Como el puerto 53 está asociado al tráfico del protocolo DNS, sabemos que este es un problema del servidor DNS. Los problemas al ejecutar el protocolo DNS son aún más evidentes porque el signo de más tras el número de identificación de consulta 35084 indica banderas con el mensaje UDP y el símbolo 'A?' indica banderas al realizar operaciones del protocolo DNS.", "C.	Debido al mensaje de respuesta de error ICMP sobre el puerto 53, es muy probable que el servidor DNS no esté respondiendo. Esta suposición se apoya además por las banderas asociadas al mensaje UDP saliente y la recuperación del nombre de dominio."],
    "Explicación": [
        "A.	Incluye un breve resumen del análisis de registros de tcpdump e identifica qué protocolos se usaron para el tráfico de red. El escenario resume el problema e identifica los protocolos utilizados. El escenario dice: 'Para cargar la página web, tu navegador primero envía una consulta a un servidor DNS a través del protocolo UDP para recuperar la dirección IP del nombre de dominio del sitio web; esto forma parte del protocolo DNS... El analizador muestra que cuando envías paquetes UDP al servidor DNS, recibes paquetes ICMP que contienen el mensaje de error: puerto udp 53 inaccesible.",
        "B.	Proporciona algunos detalles sobre lo que se indicó en el registro. El primer y segundo paso de la sección de escenario indican que realizaste un análisis de red usando tcpdump, que registró paquetes UDP desde tu ordenador de origen a la dirección IP y puerto del servidor DNS (203.0.113.2.domain). También grababa las respuestas de error ICMP del servidor DNS de vuelta a tu ordenador con el mensaje de error 'puerto udp 53 inalcanzable.' Mencionamos en el sexto paso que el puerto 53 es un puerto para el servicio DNS, lo que significa que este es un problema del servidor DNS. Incluimos más señales de problemas con el rendimiento del DNS en el quinto paso del escenario: El signo más después del número de identificación de la consulta indica que hay banderas asociadas al mensaje UDP. La 'A?' indica una bandera asociada a la solicitud DNS para un registro A, donde un registro A asigna un nombre de dominio a una dirección IP.",
        "C.	Interpreta los problemas encontrados en el registro. La sección de Escenario (o una búsqueda rápida en internet de 'puerto 53') mostrará que este número de puerto se usa comúnmente para comunicaciones con protocolos DNS. Dado que el puerto 53 es inalcanzable y ese puerto se usa comúnmente para comunicaciones con servidores DNS, se puede concluir que el servidor DNS es inalcanzable o que 'no responde'. Esto podría ser causado por un ataque DoS contra el servidor DNS, por ejemplo."]
    }

tabla_01 = pd.DataFrame(data_01)

pd.set_option('display.max_colwidth', None)

display(tabla_01.style.hide(axis="index"))

In [13]:
data_02 = {
    "Explicar el análisis de los datos y proporciona al menos una causa del incidente": [
        "D.	El incidente ocurrió hoy a la 1:24 p.m.",
        "E.	Los clientes notificaron a la organización que recibieron el mensaje 'puerto de destino inalcanzable' cuando intentaron visitar la web yummyrecipesforme.com.",
        "F.	El equipo de ciberseguridad que proporciona servicios de IT a su organización cliente está investigando actualmente el problema para que los clientes puedan acceder de nuevo a la web.",
        "G.	En nuestra investigación sobre el problema, realizamos pruebas de detección de paquetes usando tcpdump. En el archivo de registro resultante, descubrimos que el puerto DNS 53 era inaccesible.",
        "H.	El siguiente paso es identificar si el servidor DNS está caído o si el tráfico hacia el puerto 53 está bloqueado por el firewall.",
        "I.	El servidor DNS podría estar caído debido a un ataque de denegación de servicio exitoso o a una mala configuración."],
    "Explicación": [
        "D. Indica cuándo se reportó el problema por primera vez. Esta información se obtuvo de las marcas de fecha y hora del archivo de registro. En el registro, esta es la primera secuencia de números mostrada: 13:24:32.192571. Esto muestra la hora 1:24 p.m., 32,192571 segundos, con la hora en formato de 24 horas. El escenario indica que este suceso ocurrió hoy.",
        "E.	Proporciona el escenario, los eventos y los síntomas identificados cuando se reportó por primera vez. El escenario indica que, un puñado de clientes contactó con tu empresa para informar que no pudieron acceder a la web de la empresa y vieron el error 'puerto de destino inalcanzable' tras esperar a que cargara la página.",
        "F.	Explica el estado actual del problema. El Escenario afirma que, 'Este incidente, mientras tanto, está siendo gestionado por ingenieros de seguridad después de que usted y otros analistas hayan informado del problema a su supervisor directo.'",
        "G.	Describe la información descubierta investigando el problema hasta este momento. Ofrece un resumen conciso de lo que hiciste para investigar el problema. El escenario indica: Visitas la web y también recibes el error 'puerto de destino inaccesible.' Después, cargas tu herramienta de análisis de red, tcpdump y vuelves a cargar la página web. Esta vez, recibes muchos paquetes en tu analizador de red. En el analizador, envías paquetes UDP y recibes una respuesta ICMP para devolverla al host. Los resultados contienen un mensaje de error: 'puerto udp 53 inaccesible'.",
        "H.	Enumera los siguientes pasos para solucionar el problema y la resolución del problema. El siguiente paso en la resolución de problemas es determinar si el servidor DNS no funciona correctamente. Si el servidor DNS está bien, el equipo debería revisar la configuración del firewall para ver si alguien ha cambiado la configuración para bloquear el tráfico de red en el puerto 53. Los cortafuegos ofrecen la capacidad de bloquear el tráfico de red en puertos específicos. El bloqueo de puertos puede usarse para detener o prevenir un ataque.",
        "I.	Proporciona la causa raíz sospechosa del problema. Anteriormente, aprendiste sobre varios tipos de ataques de denegación de servicio (DoS). El objetivo de un ataque DoS es enviar una avalancha de información a un dispositivo de red, como un servidor DNS, para que se bloquee o impida que pueda responder al tráfico legítimo de red. Es posible que un atacante haya deshabilitado el servidor DNS con un ataque DoS. Alternativamente, alguien de tu equipo podría haber hecho un cambio de configuración en el cortafuegos que bloqueara el puerto 53."]
    }

tabla_02 = pd.DataFrame(data_02)

pd.set_option('display.max_colwidth', None)

display(tabla_02.style.hide(axis="index"))



---

*B. Informe de Incidente de Seguridad*

**Sección 1: Identificar el protocolo de red implicado en el incidente**

El protocolo implicado en el incidente es el protocolo de transferencia de hipertexto (HTTP). Como el problema era acceder al servidor web durante yummyrecipesforme.com, sabemos que las solicitudes a servidores web para páginas web implican tráfico http. Además, cuando ejecutamos tcpdump y accedimos a la web yummyrecipesforme.com el archivo de registro correspondiente de tcpdump mostró el uso del protocolo http al contactar con el servidor. Se observa que el archivo malicioso es transportado a los ordenadores de los usuarios usando el protocolo HTTP en la capa de aplicación.

**Sección 2: Documentar el incidente**

Varios clientes contactaron con el servicio de ayuda del sitio web indicando que, al visitarlo, se les pidió que descargaran y ejecutaran un archivo que contenía acceso a nuevas recetas. Sus ordenadores personales han funcionado lentamente desde entonces. El propietario de la web intentó iniciar sesión en el servidor web, pero notó que estaba bloqueado en su cuenta.

El analista de ciberseguridad utilizó un entorno sandbox para abrir la web sin afectar la red de la empresa. Luego, el analista ejecutaba tcpdump para capturar los paquetes de tráfico de red generados al interactuar con el sitio web. Se le pidió al analista que descargara un archivo que afirmaba que daría acceso a recetas gratuitas, aceptó la descarga y la ejecutó. El navegador redirigía entonces al analista a una web falsa (greatrecipesforme.com).

El analista de ciberseguridad inspeccionó el registro de tcpdump y observó que el navegador solicitó inicialmente la dirección IP del sitio web yummyrecipesforme.com. Una vez establecida la conexión con el sitio web a través del protocolo HTTP, el analista recordó haber descargado y ejecutado el archivo. Los registros mostraron un cambio repentino en el tráfico de red cuando el navegador solicitó una nueva dirección IP para la URL greatrecipesforme.com. El tráfico de red se redirigía entonces a la nueva dirección IP del sitio web greatrecipesforme.com.

El profesional senior de ciberseguridad analizó el código fuente de los sitios web y el archivo descargado. El analista descubrió que un atacante había manipulado la web para añadir código que incitaba a los usuarios a descargar un archivo malicioso disfrazado de actualización del navegador. Como el propietario del sitio web declaró que había sido bloqueado fuera de su cuenta de administrador, el equipo cree que el atacante utilizó un ataque de fuerza bruta para acceder a la cuenta y cambiar la contraseña de administrador. La ejecución del archivo malicioso comprometió los ordenadores de los usuarios finales.

**Sección 3: Recomendar una remediación para ataques de fuerza bruta**

Una medida de seguridad que el equipo planea implementar para protegerse de ataques de fuerza bruta es impedir que se usen contraseñas anteriores. Dado que la vulnerabilidad que llevó a este ataque fue la capacidad del atacante para usar una contraseña predeterminada para iniciar sesión, es importante que evitemos que se utilicen contraseñas antiguas, como las predeterminadas, para restablecer la contraseña. Otra medida de apoyo es exigir actualizaciones de contraseña más frecuentes, para que en caso de que alguna persona no autorizada se entere de la contraseña, sea menos probable que pueda usarla si se actualiza pronto. Finalmente, otra solución útil es implementar la autenticación en dos factores (2FA). La autenticación en 2FA requiere autenticación mediante contraseña y también confirmando un código de acceso único (OTP) enviado a su correo electrónico o teléfono. Una vez que el usuario confirma su identidad a través de sus credenciales de acceso y el OTP, tendrá acceso al sistema. Cualquier actor malicioso que intente un ataque por fuerza bruta probablemente no tendrá acceso al sistema porque requiere autenticación adicional.



---

*C. Evaluación de riesgos de seguridad*

**Herramientas y métodos de endurecimiento (hardering) a implementar**

Tres herramientas de endurecimiento que la organización puede utilizar para abordar las vulnerabilidades encontradas incluyen:
1.   Implementación de la autenticación multifactor (MFA)
2.   Establecimiento y aplicación de políticas de contraseñas fuertes
3.   Realizar mantenimiento de firewalls regularmente

La MFA requiere que los usuarios utilicen más de una forma de identificar y verificar sus credenciales antes de acceder a una aplicación. Algunos métodos de MFA incluyen escaneos de huellas dactilares, tarjetas de identidad, números PIN y contraseñas.

Las políticas de contraseñas pueden refinarse para incluir normas sobre la longitud de la contraseña, una lista de caracteres aceptables y un aviso para desalentar el intercambio de contraseñas. También pueden incluir reglas sobre intentos de inicio de sesión fallidos, como que el usuario pierda acceso a la red tras cinco intentos fallidos.

El mantenimiento del firewalls implica revisar y actualizar regularmente las configuraciones de seguridad para anticiparse a posibles amenazas.

**Recomendaciones**

Hacer cumplir la autenticación multifactor (**MFA**) añade una capa adicional de seguridad más allá de la simple contraseña. Esto reducirá la probabilidad de que un actor malicioso pueda acceder a una red mediante un ataque de fuerza bruta o relacionado, ya que se requiere un esfuerzo adicional para autenticarse de más de una manera. La MFA también puede reducir la probabilidad de que las personas compartan contraseñas. Dado que el destinatario de la contraseña compartida necesitaría poseer autenticación adicional además de la contraseña, la MFA hace menos útil compartir contraseñas, lo que hace menos probable que se compartan.

Crear y hacer cumplir una política de contraseñas dentro de la empresa hará que sea cada vez más difícil para los actores maliciosos acceder a la red. Políticas como suspender la cuenta tras cierto número de inicios de sesión pueden evitar ataques de fuerza bruta exitosos. Aumentar la complejidad de las contraseñas, requerir actualizaciones más frecuentes y no permitir que se reutilicen las contraseñas también ayuda a frenar la infiltración de actores maliciosos en la red.

El mantenimiento del firewall debería hacerse de forma regular. Los administradores de red deben asegurarse de que existan normas de firewalls que reflejen los estándares más actualizados para el tráfico permitido y denegado. El tráfico procedente de fuentes sospechosas debe incluirse en una lista de tráfico denegado. Las reglas del firewalls deben actualizarse siempre que ocurra un evento de seguridad, especialmente un evento que permita la entrada de tráfico sospechoso en la red. Esta medida puede usarse para proteger contra diversos ataques DoS (Denial-of-Service) y DDoS (Distributed Denial-of-Service).



---

*D. Análisis del informe de incidentes*

**Resumen:**
La empresa experimentó un evento de seguridad cuando todos los servicios de red dejaron de responder de repente. El equipo de ciberseguridad encontró que la interrupción fue causada por un ataque de denegación de servicios distribuida (DDoS) a través de una avalancha de paquetes ICMP entrantes. El equipo respondió bloqueando el ataque y deteniendo todos los servicios de red no críticos, para que se pudieran restaurar los servicios críticos.

In [18]:
data_report = {
    "NIST CSF": [
        "Identificar",
        "Proteger",
        "Detectar",
        "Responder",
        "Recuperar"],
    "Descripción": [
        "Un actor malicioso o actores maliciosos atacaron a la empresa con un ataque de inundación ICMP. Toda la red interna se vio afectada. Todos los recursos críticos de la red debían asegurarse y restaurarse a un estado funcional.",
        "El equipo de ciberseguridad implementó una nueva regla de firewalls para limitar la tasa de paquetes ICMP entrantes y un sistema IDS/IPS para filtrar parte del tráfico ICMP según características sospechosas.",
        "El equipo de ciberseguridad configuró la verificación de direcciones IP de origen en el firewalls para comprobar si las direcciones IP suplantadas en paquetes ICMP entrantes e implementó software de monitorización de red para detectar patrones de tráfico anormales.",
        "Para futuros eventos de seguridad, el equipo de ciberseguridad aislará los sistemas afectados para evitar más interrupciones en la red. Intentarán restaurar cualquier sistema y servicio crítico que haya sido interrumpido por el evento. Luego, el equipo analizará los registros de red para comprobar si hay actividad sospechosa o anormal. El equipo también informará de todos los incidentes a la alta dirección y a las autoridades legales correspondientes, si procede.",
        "Para recuperarse de un ataque DDoS por inundación ICMP, es necesario restaurar el acceso a los servicios de red a un estado de funcionamiento normal. En el futuro, los ataques externos de inundación ICMP pueden bloquearse en el cortafuegos. Entonces, todos los servicios de red no críticos deben detenerse para reducir el tráfico interno de red. A continuación, primero se deben restablecer los servicios críticos de red. Finalmente, una vez que la avalancha de paquetes ICMP ha expirado, todos los sistemas y servicios de red no críticos pueden volver a estar en línea."]
    }

tabla_report = pd.DataFrame(data_report)

pd.set_option('display.max_colwidth', None)

display(tabla_report.style.hide(axis="index"))