#**Ejercicios de Aprendizaje**

###**05_Diario de Incidentes y Reporte Final**

*A. Incidente de Ransonware ocurrido por culpa de hackers*

*Nota adicional: Las 5 W's Que se mencionan hacenalucion a las 5 incognitas a resolver donde W indica la letra inicial en el idioma original (ingles), con los cual significan:* **Who**, **What**, **Where**, **When**, **Why**.

In [3]:
import pandas as pd

data_incident1 = {
    "Fecha": [
        "17 de Abril de 2026",
        "Descripción",
        "Herramienta(s) utilizada(s)",
        "Las 5 W's",
        "Notas Adicionales"
    ],
    "Entrada": [
        "#1",
        "Este incidente ocurrió en dos fases: 1.	Detección y análisis: El escenario describe cómo la organización detectó por primera vez el incidente de ransomware. Para el paso de análisis, la organización contactó con varias organizaciones para recibir asistencia técnica. 2.	Contención, erradicación y recuperación: El escenario detalla algunos pasos que la organización tomó para contener el incidente. Por ejemplo, la empresa apagó sus sistemas informáticos. Sin embargo, como no pudieron trabajar solo para erradicar y recuperarse del incidente, contactaron con varias otras organizaciones para pedir ayuda.",
        "-",
        "●	Quién: Un grupo organizado de hackers sin ética ●	Qué: Un incidente de seguridad de ransomware ●	Dónde: En una empresa sanitaria ●	Cuándo: martes a las 9:00 a.m. ●	Por qué: El incidente ocurrió porque hackers poco éticos pudieron acceder a los sistemas de la empresa mediante un ataque de phishing. Tras obtener el acceso, los atacantes lanzaron su ransomware contra los sistemas de la empresa, cifrando archivos críticos. La motivación de los atacantes parece ser financiera, ya que la nota de rescate que dejaron exigía una gran suma de dinero a cambio de la clave de descifrado.",
        "1.	¿Cómo podría la empresa sanitaria evitar que un incidente así vuelva a ocurrir? 2.	¿Debería la empresa pagar el rescate para recuperar la clave de descifrado?"
    ]
}

table_incident1 = pd.DataFrame(data_incident1)

pd.set_option('display.max_colwidth', None)

display(table_incident1.style.hide(axis="index"))



---

In [4]:
data_incident2 = {
    "Fecha": [
        "19 de Abril de 2026",
        "Descripción",
        "Herramienta(s) utilizada(s)",
        "Las 5 W's",
        "Notas Adicionales"
    ],
    "Entrada": [
        "#2",
        "Análisis de un archivo de captura de paquetes",
        "Para esta actividad, utilicé Wireshark para analizar un archivo de captura de paquetes. Wireshark es un analizador de protocolos de red que utiliza una interfaz gráfica de usuario. El valor de Wireshark en ciberseguridad es que permite a los analistas de seguridad capturar y analizar el tráfico de red. Esto puede ayudar a detectar e investigar actividades maliciosas.",
        "●	Quién: N/A ●  Qué: N/A ●	Dónde: N/A ●	Cuándo: N/D ●	Por qué: N/A",
        "Nunca había usado Wireshark antes, así que estaba emocionado por comenzar este ejercicio y analizar un archivo de captura de paquetes. A primera vista, la interfaz era muy abrumadora. Puedo entender por qué es una herramienta tan potente para entender el tráfico de red."
    ]
}

table_incident2 = pd.DataFrame(data_incident2)

pd.set_option('display.max_colwidth', None)

display(table_incident2.style.hide(axis="index"))



---

In [5]:
data_incident3 = {
    "Fecha": [
        "19 de Abril de 2026",
        "Descripción",
        "Herramienta(s) utilizada(s)",
        "Las 5 W's",
        "Notas Adicionales"
    ],
    "Entrada": [
        "#3",
        "Capturando mi primer paquete",
        "Para esta actividad, utilicé tcpdump para capturar y analizar el tráfico de red. Tcpdump es un analizador de protocolos de red al que se accede mediante la interfaz de línea de comandos. Similar a Wireshark, el valor de tcpdump en ciberseguridad es que permite a los analistas de seguridad capturar, filtrar y analizar el tráfico de red.",
        "●	Quién: N/A ●  Qué: N/A ●	Dónde: N/A ●	Cuándo: N/D ●	Por qué: N/A",
        "Todavía soy nuevo usando la interfaz de línea de comandos, así que usarla para capturar y filtrar el tráfico de red fue un reto. Me quedé atascado un par de veces porque usé los comandos equivocados. Pero tras seguir cuidadosamente las instrucciones y repetir algunos pasos, pude superar esta actividad y capturar tráfico de red."
    ]
}

table_incident3 = pd.DataFrame(data_incident3)

pd.set_option('display.max_colwidth', None)

display(table_incident3.style.hide(axis="index"))



---

In [10]:
data_incident4 = {
    "Fecha": [
        "20 de Abril de 2026",
        "Descripción",
        "Herramienta(s) utilizada(s)",
        "Las 5 W's",
        "Notas Adicionales"
    ],
    "Entrada": [
        "#4",
        "Investigar un hash de archivo sospechoso",
        "Para esta actividad, utilicé VirusTotal, que es una herramienta de investigación que analiza archivos y URLs en busca de contenido malicioso como virus, gusanos, troyanos y más. Es una herramienta muy útil si quieres comprobar rápidamente si un indicador de compromiso, como una web o archivo, ha sido reportado como malicioso por otras personas en la comunidad de ciberseguridad. Para esta actividad, utilicé VirusTotal para analizar un hash de archivo, que fue reportado como malicioso. Este incidente ocurrió en la  fase de Detección y Análisis. El escenario me situó en el lugar de un analista de seguridad en un SOC investigando un hash de archivo sospechoso. Después de que los sistemas de seguridad detectaran el archivo sospechoso, tuve que realizar un análisis e investigación más profundos para determinar si la alerta significaba una amenaza real.",
        "●	Quién: Un actor malicioso desconocido ●	Qué: Un correo enviado a un empleado contenía un archivo adjunto malicioso con el hash SHA-256 de 54e6ea47eb04634d3e87fd7787e2136ccfbcc80ade34f246a12cf93bab527f6b ●	Dónde: El ordenador de un empleado en una empresa de servicios financieros ●	Cuándo: A la 1:20 p.m., se envió una alerta al SOC de la organización tras la detección de intrusiones del archivo ●	Por qué: Un empleado pudo descargar y ejecutar un archivo adjunto malicioso mediante correo electrónico.",
        "1. ¿Cómo se puede prevenir este incidente en el futuro? 2. ¿Deberíamos considerar mejorar la formación en concienciación de seguridad para que los empleados sean cuidadosos con lo que hacen clic? "
    ]
}

table_incident4 = pd.DataFrame(data_incident4)

pd.set_option('display.max_colwidth', None)

display(table_incident4.style.hide(axis="index"))



---

In [9]:
data_extras = {
    "Cuestiones": [
        "1.	¿Hubo alguna actividad concreta que resultara un reto para ti? ¿Por qué o por qué no?",
        "2.	¿Ha cambiado tu comprensión sobre la detección y respuesta a incidentes tras hacer este curso?",
        "3.	¿Hubo alguna herramienta o concepto específico que disfrutaste más? ¿Por qué?"
    ],
    "Reflexiones/Notas": [
        "Realmente encontré desafiante la actividad utilizando tcpdump. Soy nuevo usando la línea de comandos, y aprender la sintaxis de una herramienta como tcpdump fue una gran curva de aprendizaje. Al principio, me sentí un poco frustrado porque no obtenía el resultado correcto. Rehice la actividad y descubrí dónde había fallado. Lo que aprendí de esto fue leer cuidadosamente las instrucciones y avanzar despacio en el proceso.",
        "Después de hacer este curso, mi comprensión de la detección y respuesta a incidentes ha evolucionado definitivamente. Al principio del curso, tenía una comprensión básica de lo que implicaba la detección y la respuesta, pero no comprendía completamente la complejidad que implicaba. A medida que avanzaba en el curso, aprendí sobre el ciclo de vida de un incidente; la importancia de los planes, procesos y personas; y las herramientas utilizadas. En general, siento que mi comprensión ha cambiado y estoy equipado con más conocimientos y comprensión sobre la detección y respuesta a incidentes.",
        "Disfruté mucho aprendiendo sobre análisis de tráfico de red y aplicando lo que aprendí a través de herramientas de análisis de protocolos de red. Fue la primera vez que aprendí sobre análisis de tráfico de red, así que fue tanto un reto como emocionante. Me pareció realmente fascinante poder usar herramientas para capturar y analizar el tráfico de red en tiempo real. Sin duda me interesa más aprender más sobre este tema, y espero algún día volverme más competente usando herramientas de análisis de protocolos de red. "
    ]
}

table_extras = pd.DataFrame(data_extras)

pd.set_option('display.max_colwidth', None)

display(table_extras.style.hide(axis="index"))



---

*B. Reporte final de acceso no autorizado a datos de clientes*

###*Informe Final del Incidente*

**Resumen ejecutivo**

La organización experimentó un incidente de seguridad el 19 de Abril de 2026, a las 19:20 hora, durante el cual una persona pudo obtener acceso no autorizado a información personal identificable (PII) de clientes e información financiera. Se vieron afectados aproximadamente 50.000 registros de clientes. El impacto financiero del incidente se estima en 100.000 dólares en costes directos y posibles pérdidas de ingresos. El incidente ya está cerrado y se ha llevado a cabo una investigación exhaustiva.

**Cronología**

Aproximadamente a las 15:13 hora, el 20 de Abril de 2026, un empleado recibió un correo electrónico de una dirección externa. El remitente afirmó que había conseguido robar datos de clientes. A cambio de no facilitar los datos en foros públicos, el remitente solicitó un pago en criptomonedas de 25.000 dólares. El empleado asumió que el correo era spam y lo eliminó.
El 22 de diciembre de 2026, el mismo empleado recibió otro correo electrónico del mismo remitente. Este correo incluía una muestra de los datos robados de clientes y una demanda de pago aumentada de 50.000 dólares.
Ese mismo día, el empleado notificó al equipo de seguridad, que inició la investigación sobre el incidente. Entre el 22 y el 25 de Abril de 2026, el equipo de seguridad se centró en determinar cómo se robaron los datos y la magnitud del robo.

**Investigación**

El equipo de seguridad recibió la alerta y viajó al lugar para comenzar la investigación.
La causa raíz del incidente se identificó como una vulnerabilidad en la aplicación web de comercio electrónico. Esta vulnerabilidad permitía al atacante realizar un ataque de navegación forzada y acceder a los datos de transacciones del cliente modificando el número de pedido incluido en la cadena URL de una página de confirmación de compra. Esta vulnerabilidad permitía al atacante acceder a las páginas de confirmación de compra del cliente, exponiendo los datos del cliente, que luego recogía y exfiltraba.
Tras confirmar la vulnerabilidad de la aplicación web, el equipo de seguridad analizó los registros de acceso a la aplicación web. Los registros indicaban que el atacante accedió a la información de miles de páginas de confirmación de compras.

**Respuesta y remediación**

La organización colaboró con el departamento de relaciones públicas para divulgar la brecha de datos a sus clientes. Además, la organización ofreció servicios gratuitos de protección de identidad a los clientes afectados por el incidente.
Después de que el equipo de seguridad revisara los registros asociados del servidor web, la causa del ataque quedó muy clara. Había una única fuente de registro que mostraba un volumen excepcionalmente alto de pedidos de clientes listados secuencialmente.

**Recomendaciones**

Para evitar que se repitan en el futuro, estamos tomando las siguientes medidas:

●	Realizar escaneos rutinarios de vulnerabilidades y pruebas de penetración.

●	Implementa los siguientes mecanismos de control de acceso:

    ○	Implementa la lista de permisos para permitir el acceso a un conjunto específico de URLs y bloquea automáticamente todas las solicitudes fuera de este rango de URL.

    ○	Asegúrate de que solo los usuarios autenticados tengan acceso autorizado al contenido.